### PR TITLE
[Django Upgrade] [ENG-3947] Update markdown extension

### PR DESCRIPTION
**Pull request by Johnetordoff**
## Purpose

Old versions of markdowns python library no longer work with Django so we have to upgrade Markdown to be compatible and update a few functions.Additionally Our forked markdown extension library https://github.com/CenterForOpenScience/mdx_del_ins/ is no longer compatible with markdown, so it had to have a minor fork. https://github.com/CenterForOpenScience/mdx_del_ins/pull/1

https://www.notion.so/cos/6188c43512ee482586da59bc5fdacf38?v=bb051c7d4d7346d69d9fcbbc979dd883&p=02a1b6368b0b47fbbab07a01d88135d9&pm=s

Error:
https://gist.github.com/Johnetordoff/84c900be9f2427db40ac57d18386cf6f

## Changes

- updates markdown to use new format for passing arguments
- forks mdx_del_ins to work with new version of markdown.

## QA Notes

Please make verification statements inspired by your code and what your code touches.
- Verify
- Verify

What are the areas of risk?

Any concerns/considerations/questions that development raised?

### CODE REVIEW

File: requirements.txt [hunk 1]
```diff
@@ -39,7 +39,7 @@ django-waffle==0.13.0
 pymongo==3.7.1
 tqdm==4.28.1
 # Python markdown extensions for comment emails
-git+https://github.com/CenterForOpenScience/mdx_del_ins.git
```
Comment (Johnetordoff) [inline requirements.txt:42]: https://github.com/CenterForOpenScience/mdx_del_ins/pull/1

**Review by cslzchen — COMMENTED** [review]
This markdown upgrade is not listed in our incompatibility list. My guess is that the incompatibility is caused by upgrading the markdown instead of django 3. Will merge this one later.

**Comment by Johnetordoff** [comment]
@cslzchen After replicating this issue, it seems that the markdown problem was caused by a DRF incompatibility [Error](https://gist.github.com/Johnetordoff/84c900be9f2427db40ac57d18386cf6f) I'm looking to see if there's a version of DRF that works with both Django 3.2 and our current markdown, but it doesn't look like there's a version that satisfies both, so changing Markdown seems easiest.

**Comment by cslzchen** [comment]
> @cslzchen After replicating this issue, it seems that the markdown problem was caused by a DRF incompatibility [Error](https://gist.github.com/Johnetordoff/84c900be9f2427db40ac57d18386cf6f) I'm looking to see if there's a version of DRF that works with both Django 3.2 and our current markdown, but it doesn't look like there's a version that satisfies both, so changing Markdown seems easiest.

Ah, I see. I remember this `AttributeError: 'OrderedDict' object has no attribute 'register'` error on one of my reference PRs too. Let me take another look at this one.

File: requirements.txt [hunk 2]
```diff
@@ -40,7 +40,7 @@ pymongo==3.7.1
 PyYAML==6.0
 tqdm==4.28.1
 # Python markdown extensions for comment emails
-git+https://github.com/CenterForOpenScience/mdx_del_ins.git
+git+https://github.com/Johnetordoff/mdx_del_ins.git@django-3
```
Comment (cslzchen) [inline requirements.txt:43]: Added to post-release update where we will merge your of `mdx_del_ins.git` and revert the requirement pinging.

**Review by cslzchen — APPROVED** [review]
As discussed, the reason why we have to upgrade `markdown` is because we have to upgrade `djangrestframwork` due to `django` upgrade. Cc @jh27539  I will ask QA to manually test project wiki page after deployment on staging3.
